workflows:
  nova-os:
    name: Nova OS Build

    environment:
      java: 17
      android: true

    scripts:
      - name: Check files
        script: ls -la

      - name: Install Gradle
        script: |
          sdkmanager "platform-tools" "platforms;android-36"

      - name: Make gradle wrapper (fix)
        script: gradle wrapper || true

      - name: Build Debug APK
        script: gradle assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
